name: Backend CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'nutriz-backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    name: Run backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nutriz-backend
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: nutriz-backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest suite
        run: npm test
        env:
          CI: true
